[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ComradeBase = "6d8c423b-a35f-4ef1-850c-862fe21f82c4"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
FieldDimArrays = "8162b97e-af21-446d-9d6e-57a067fd3c83"

[sources]
ComradeBase = {path = ".."}
FieldDimArrays = {url = "https://github.com/ptiede/FieldDimArrays.jl", rev = "main"}
